---
apiVersion: v1
kind: ConfigMap
metadata:
  name: policy-bundle
  namespace: default
binaryData:
  bundle.tar.gz: H4sIAAAAAAAA/+xYbW/CNhDuV/wrTqaV2olR8z5FZb+gH6Z9RShyyUG9JXaWOGsZ4r9Pl1cIIFg7Wm3KfWhS53zPc3buOYdHT1rZ/S02+uZqJoQQYyHSqzi80sPqnsZ7PTEa3oC4HqXKktjK6EZ8Gque3H/ENhyD0DdrxJg7M76M0OMd/iIjjWu6QWvp+qb8QPL5ln0338b+XXsMja8W626EK3MtjDP13xv3Dup/2J809f8VFsrF73KFIBP7+hdjHi5l4luQvm/eYApL6cfIWBt+xVXiywhKtYCF1IDvIeoY4QkGQrBs0oa1VOwWfqy1iqSHrl2HeM+jLAp/YC2lw8R2E63sL5FaIPwA2cgfidRW2TU8TfORHORZBcpeNm8kBNsS62eUXp3p6CKmFmXwo4/S+wTXLa2nXs+4NraE4XOYQkDY2ljYww/AmUIcRkrb5T2/i0HFQE5Ev5jdgVmGpGWA84cKA98XiJ6bE3B9YlBhycAk2kJB83QqpevPR1d/n+LtnQcZbrm+KS6YJdzeeUQ2i9Y5EuwI+WwDatRPvD8fyYi2/nQKKdBOAiMhqgwytjvbRdTSs1NZETN3XtKh3aEJO+TpzwPNopvSMXVg39dXc/13Lcb2Wk3gnP5Pxv2a/veHk3Gj/19hNf1vV/o+hRlrtzbA6V3mDuRnQ+DpK0sDRTXCtrPvWRwfL/HNTpa7rpX0dmheaCIbcwdmFYM8Psxhy9pzxkLjCphSbdXIstYhAxos1YI70BOChgq54A706f9dqeIO9bcOFXRo3F4Nqsj2ErD+RWDDCqz/CbDBRWCTCmxQA8v3ZhdrZ3POpjY4gvZThTYktBIrxJcXH2O+ZYy0yKUNdPPM3DdlX5Xeb25pW0v7OD3N5BRkDPQysCJKtlwfjdM7FSfvVwsThFKvqzhptz4eq1/GSlfVpYV0fZT6n5IalIHyJXPpeJE6o3eGxPCg0zx2A6nVEmN7PY05+/0/mBx8/48Hjf5/hW14hH+qWBnNHR4J3uGRMTb9LaD53G+sscYa+x/b3wEAAP//EZAmfAAYAAA=

---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: rbac-example
   labels:
      name: rbac-example

spec:
   replicas: 1
   selector:
      matchLabels:
         name: rbac-example
   template:
      metadata:
         name: rbac-example
         labels:
            name: rbac-example
      spec:
         volumes:
         - name: policy-bundle-vol 
           configMap: 
               name: policy-bundle
         containers:
         - name: webapp
           image: chukmunnlee/demo-rbac:v1
           imagePullPolicy: IfNotPresent

         - name: opa
           #image: openpolicyagent/opa:0.34.0-dev-static
           image: openpolicyagent/opa:latest
           args: [ "run", "-s", "-b", "/policy/bundle.tar.gz" ]
           volumeMounts:
           - name: policy-bundle-vol
             mountPath: /policy

